apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app-name: nginx
    type: front-end
spec:
  containers:
    - name: nginx
      image: nginx
#>kubectl <apply/create> -f pod-definition.yml
