apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app-name: nginx
    type: front-end
spec:
  type: NodePort
  selector:
    app-name: nginx
    type: front-end
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
