apiVersion: v1
kind: Service
metadata:
  name: results-app
spec:
  type: NodePort
  selector:
    name: results-app
    app: voting-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
