apiVersion: v1
kind: Pod
metadata:
  name: results-app
  labels:
    name: results-app
    app: voting-app
spec:
  containers:
    - name: results-app
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80
