apiVersion: v1
kind: Service
metadata:
  name: voting-app
spec:
  type: NodePort
  selector:
    name: voting-poll
    app: voting-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
